version: "3.9"
services:
  strapi:
    image: strapi/strapi
    container_name: strapi
    environment:
      DATABASE_CLIENT: mysql
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_NAME: me
      DATABASE_USERNAME: tom
      DATABASE_PASSWORD: xDd0283#da6844D*xH3jhj
      DATABASE_SSL: 'false'
    volumes:
      - ./backend:/srv/app
    ports:
      - '1337:1337'
    depends_on:
      - mysql
      

  mysql:
    image: mysql
    cap_add:
      - SYS_NICE  
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: xDk849mduWxD(dwe&
      MYSQL_DATABASE: me
      MYSQL_USER: tom
      MYSQL_PASSWORD: xDd0283#da6844D*xH3jhj

  frontend:
    build: ./frontend
    ports:
      - 3000:3000

  